### PR TITLE
newbranch: add comment for pull request

### PR DESCRIPTION
**Pull request by Wdeschry**
Pull request for newbranch

### CODE REVIEW

**Comment by ser316asu** [comment]
I approve this PR, I did not check any specifics on it though

**Review by Wdeschry — COMMENTED** [review]
reviewing changed files

**Review by ser316asu — APPROVED** [review]
I approve this PR, I did not check any specifics on it though

**Review by ser316asu — APPROVED** [review]

**Review by ser316asu — APPROVED** [review]
I approve this PR, I did not check any specifics on it though

**Pull request merged**
